AWSTemplateFormatVersion: '2010-09-09'
Description: >
  eShelf - VPC stack (Lab 1/2 CloudFormation skeleton).
  Tạo VPC, public/private subnets, IGW.

Parameters:
  ProjectName:
    Type: String
    Default: eshelf

Resources:
  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-vpc'

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-igw'

  VpcGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref Vpc
      InternetGatewayId: !Ref InternetGateway

Outputs:
  VpcId:
    Description: ID of the VPC
    Value: !Ref Vpc


